// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type FeedbackPostRequest struct {
	ProductID string  `json:"productId"`
	Rating    int     `json:"rating"`
	Feedbacks *string `json:"feedbacks"`
}

type FeedbackResponse struct {
	FeedbackID string    `json:"feedbackId"`
	ProductID  string    `json:"productId"`
	Rating     int       `json:"rating"`
	Feedbacks  *string   `json:"feedbacks"`
	CreatedAt  time.Time `json:"createdAt"`
}
